apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-job-service
  labels:
    app: print-job-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: print-job-service
  template:
    metadata:
      labels:
        app: print-job-service
    spec:
      containers:
        - name: print-job-service
          image: print-job-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: print-job-service-db
                  key: dbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: print-job-service-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: print-job-service-db
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5